# Generated by Django 4.0.2 on 2022-02-20 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8f335884-e4a2-41cd-b570-af7dac08eea1'), primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('member_count', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Member_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Groups',
                'ordering': ['title'],
            },
        ),
    ]
