# Generated by Django 4.0.2 on 2022-02-21 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_groupmember_id_alter_groups_id_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('664dec71-65f4-4faf-9c6f-02e892b1e52e'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0efab4f0-b0fd-4d8a-b740-92c674d3659b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groups')),
                ('like_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messages')),
            ],
        ),
    ]
