# Generated by Django 4.0.2 on 2022-02-21 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_groupmember_id_alter_groups_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2ff4069-3277-431d-8f6d-bc8c24586688'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1cf1e27-ed16-464a-8de6-201f50285ff8'), primary_key=True, serialize=False, unique=True),
        ),
    ]
